### ISSUE TITLE
Special (delayed) handling of Bundles with timestamps

### ISSUE THREAD

**Issue by hoijui** [hoijui/JavaOSC#19]
From the OSC 1.0 specifications:

> When a received OSC Packet contains only a single OSC Message, the OSC Server should invoke the correponding OSC Methods immediately, i.e., as soon as possible after receipt of the packet. Otherwise a received OSC Packet contains an OSC Bundle, in which case the OSC Bundle's OSC Time Tag determines when the OSC Bundle's OSC Messages' corresponding OSC Methods should be invoked. If the time represented by the OSC Time Tag is before or equal to the current time, the OSC Server should invoke the methods immediately (unless the user has configured the OSC Server to discard messages that arrive too late). Otherwise the OSC Time Tag represents a time in the future, and the OSC server must store the OSC Bundle until the specified time and then invoke the appropriate OSC Methods.

JavaOSC does currently not do this.

**Comment by daveyarwood** [comment]
I think it's actually better that JavaOSC does not do this. I think it should be up to the application, and it's actually better that the author of the application has control over how to implement the delay.

Case in point: I'm working an an application that listens for OSC messages and schedules music events (notes, chords, etc.) in sync with a MIDI sequence playing in real time. It's important for my application that I be able to control how to schedule events. I'm planning to use a javax.sound.midi.Sequencer, which allows you to schedule events in the future, so it would be ideal if I could schedule the events immediately, and use the time tag on the OSC message to inform how far into the future I schedule the events.

What might be nice, if we want to make it extra convenient for those who don't want to implement their own scheduler, is to provide a **separate mode of listening** where JavaOSC schedules the handling of messages according to their time tags. I'm not quite sure what the API might look like, but just wanted to throw that idea out there.

**Comment by hoijui** [comment]
thanks @daveyarwood!
very good remark and idea; all of this makes total sense to me.

**Comment by hoijui** [comment]
I just found out that this has already been implemented, here: https://github.com/hoijui/JavaOSC/commit/615e98723de55b5361ed0f82efe00dd2d94c5904
So by default, the behavior is now OSC 1.0 standard compliant, but one can turn it off, and always schedule all messages/bundles immediately with `OSCPacketDispatcher#setAlwaysDispatchingImmediately(true)`

**Comment by daveyarwood** [comment]
It looks like "always dispatch immediately" is actually the default behavior, based on the code in that commit and the behavior that I observed when testing this locally. I created a simple listener that just prints out messages, and I sent it some bundles with a timestamp 15 minutes in the future, and it always executes immediately.

At any rate, it's good that this feature is already implemented and available for anyone who might want to use it! I do think that the current behavior is a good default, for the reasons I stated above.

**Comment by hoijui** [comment]
ouhhh you are right! I have overseen the part of the code in _OSCPortIn.java_.
Hmm... I am not so happy with it. I understand your reasons, but really, it makes sense in some use-cases, and would make sense the other way around in others. The only valid arguments I see, for one or the other, is what the standard says, and what the library did so far. I personally would like to change to the standard way before the next release, because there are so many changes in the library already since the last one, that users of the library will have to heavily adjust their code anyway.
In your particular case, you can just manually set `dispatcher.setAlwaysDispatchingImmediately(true);`, and then you don't have to worry about what the library uses as standard anymore, right?

**Comment by daveyarwood** [comment]
I have no objection to changing the behavior to be closer to the specification, just as long as there is some option like `setAlwaysDispatchingImmediately` that allows me to go lower-level and decide how I want to handle the time tags, whenever I need that level of flexibility.

BTW, I did a `git grep` for `setAlwaysDispatchingImmediately` on the master branch of this repo, and it turned up no results! So apparently the implementation you linked above was removed at some point?

**Comment by hoijui** [comment]
ahhh good to hear! :-)

the commit I linked it to introduced it as:
`setAlwaysDispatchingImmediatly`
which contains a typo, which I fixed in the `develop` branch to now be:
`setAlwaysDispatchingImmediately`
the `master` branch does not contain this fix yet.

**Comment by daveyarwood** [comment]
Ah, I see it now!

**Comment by daveyarwood** [comment]
I think this issue can be closed now, as we do support this feature of OSC.
