### ISSUE TITLE
OSCPortIn.stopListening() waits until one more packet is received

### ISSUE THREAD

**Issue by uzadow** [hoijui/JavaOSC#20]
OSCPortIn stays in socket.receive() after stopListening() is called until the next network packet arrives. In a connection that is only active irregularly, this becomes an issue because the socket remains open potentially indefinitely, preventing reconnects.

Internally, the else branch of the following snippet (in OSCPortIn.run()) never gets called:

``` java
    try {
        socket.receive(packet);
    } catch (SocketException ex) {
        if (listening) {
            throw ex;
        } else {
            // if we closed the socket while receiving data,
            // the exception is expected/normal, so we hide it
            continue;
        }
    }
```

One possible fix would be to add a getSocket().close() call in stopListening(). This causes receive() to throw an exception as expected.

**Comment by hoijui** [comment]
closing as it is fixed in branch develop, see referenced commits.
Thanks again uzadow!
