### ISSUE TITLE
BUFFER_SIZE in OSCPortIn is smaller than max datagram size

### ISSUE THREAD

**Issue by RussellAult** [hoijui/JavaOSC#22]
`BUFFER_SIZE` in the `OSCPortIn` class is smaller than the maximum possible incoming datagram data size of 65507 bytes. In addition to losing the ends of long messages, this can cause `ArrayIndexOutOfBounds` run-time exceptions if the incoming OSC message is larger than the buffer size, as some of the methods in the `OSCByteArrayToJavaConverter` class will while-increment themselves past the end of the array looking for something (I found this specifically in the `lengthOfCurrentString` method, but it might also affect others).

For myself, I've resolved this by setting `private static final int BUFFER_SIZE = 65507;`.

**Comment by hoijui** [comment]
thank you! :-)
i made a commit. it will be in the next release.
https://github.com/hoijui/JavaOSC/commit/4ce67e43068db29aebb4ad8ad5ca89a084bc472a
