### ISSUE TITLE
Latest version not available on Maven central

### ISSUE THREAD

**Issue by mgsx-dev** [hoijui/JavaOSC#30]
As per README, last version should be available on maven central : http://mvnrepository.com/artifact/com.illposed.osc/javaosc-core

But recent 0.4 is not. Did you published to maven central ? or there is a kind of delay between publishing and availability ?

Thanks.

**Comment by mgsx-dev** [comment]
for people facing same issue : want to use 0.4 version while waiting for maven central availability, there's a workaround using jitpack. In your gradle build you can temporarily use this dependency :

`compile "com.github.hoijui.JavaOSC:javaosc-core:javaosc-0.4"`

note that you have to add jitpack as repository as well : 

```
repositories {
        ...
        maven { url "https://jitpack.io" }
    }
```

Hopping to have update on this issue soon :-)

**Comment by hoijui** [comment]
yeah i have a problem with signing the jars, sorry.
release procedure is kind of.. frustrating, every time, because every time, multiple things do not work, and you end up with half-done releases like this one.

**Comment by hoijui** [comment]
finally!
`javaosc-0.4` is on maven central.
i had to add an other commit to make it work, so it is not what was on the master branch as javaosc-0.4 for quite some time now, but java-code-wise, it is the same. it just differs in the README and the parent `pom.xml`.
