### ISSUE TITLE
StandardProtocolFamily requires Android API 24

### ISSUE THREAD

**Issue by Burtan** [hoijui/JavaOSC#48]
Hey,

OSCPort makes use of java.net.StandardProtocolFamily but it's only available at Android API 24 and higher. Could we replace it? StandardSocketOptions has the same problems.

**Comment by WimVriend** [comment]
Hi Burtan,

It's even worse: when compiling with the 0.6 version, the compiler complains:

> Invoke-customs are only supported starting with Android O (--min-api 26)

I am creating an App which I also want to use on older Android versions (min API 23). How do I do that?

**Comment by Burtan** [comment]
Ai, that makes it even worse. 0.4 is a version that is running with no problems under Android, however, there have been many improvements since and I would prefer to improve compatibility of the changes with android. Regarding the missing classes they could be checked for and run alternatives under Android. No idea about Invoke-customs yet.

**Comment by WimVriend** [comment]
I also 'downgraded' to 0.4 and now it works with API 23. I did run into the problem where you are not allowed to send messages on the UI thread (which of course I did to test stuff...)

For my intended purposes 0.4 works, so I will stick with that.

**Comment by Burtan** [comment]
I've created a pull request which should fix the android problems. At least my local test on my use case works.

**Comment by Burtan** [comment]
Any news on this? Would be nice to have a new version with better android compatibility.

**Comment by hoijui** [comment]
hey.. sorry! i was .. busy. ;-)
lets see this through now!

**Comment by hoijui** [comment]
solved by https://github.com/hoijui/JavaOSC/pull/49
thank you @Burtan ! :-)
