### ISSUE TITLE
Relevant version on maven

### ISSUE THREAD

**Issue by MrExplode** [hoijui/JavaOSC#54]
Can someone do a release? the latest (0.6) was more than a year ago.

**Comment by Burtan** [comment]
0.7 is on the way, snapshots are already available.

**Comment by MrExplode** [comment]
Alright since there are no changes in the codebase for more than a month now, may I ask respcetfully again to do the 0.7 release? I really don't want to set up jitpack and a custom repo just to automate my builds

**Comment by hoijui** [comment]
Released
