### ISSUE TITLE
ClassNotFound: AwtColorArgumentHandlerTest 

### ISSUE THREAD

**Issue by JellevanAbbema** [hoijui/JavaOSC#56]
I'm using the latest version of javaosc-core from maven central.
Whenever I try to send an OSC message I get the following error:
java.lang.ClassNotFoundException: com.illposed.osc.argument.handler.AwtColorArgumentHandlerTest

This is a test class and thus not included in a release, so why is the library trying to use it?

**Comment by hoijui** [comment]
HA!
thank you @JellevanAbbema!
That is an typo that slipped in... interesting it did not cause more problems so far.
It is fixed in `master` now, and wil be so in the next release (probably 0.8).
