### ISSUE TITLE
java.awt.color on android 

### ISSUE THREAD

**Issue by JellevanAbbema** [hoijui/JavaOSC#60]
I am having this issue on windows and on android using a part of this library. I am only using it to create OSC Messages with arguments and to parse it to a byteBuffer so I can send it via my own protocol. 

Error log on android:
`java.lang.NoClassDefFoundError: Failed resolution of: Ljava/awt/Color;
        at com.illposed.osc.argument.handler.AwtColorArgumentHandler.getJavaClass(AwtColorArgumentHandler.java:43)
        at com.illposed.osc.OSCSerializer.<init>(OSCSerializer.java:101)
        at com.illposed.osc.OSCSerializerAndParserBuilder.buildSerializer(OSCSerializerAndParserBuilder.java:64)`

EDIT:
So when I opened this issue I was in a hurry, but after looking at it a couple hours later I think I found the problem, kind of.
The issue is with the java.awt.color library, which is not supported on android. I found some older issues and fixes (#43, #49), so that should mean this problem souldn't exist. But apperantly it does with the latest version (0.8) of this library, maybe something slipt in?

**Comment by ManuDev9** [comment]
Hello my friends,
this is a Java workaround from the application perspective. No need to pick weird snapshots:
```
            OSCSerializerAndParserBuilder serializer = new OSCSerializerAndParserBuilder();
            serializer.setUsingDefaultHandlers(false);
            List<ArgumentHandler> defaultParserTypes = Activator.createSerializerTypes();
            defaultParserTypes.remove(16);
            char typeChar = 'a';
            for (ArgumentHandler argumentHandler:defaultParserTypes) {
                serializer.registerArgumentHandler(argumentHandler, typeChar);
                typeChar++;
            }
            mOscPortOut = new OSCPortOut(serializer,
                    new InetSocketAddress(AppData.getOscRemoteAddress(), AppData.getOscPortOutNumber()));
```
Enjoy

**Comment by hoijui** [comment]
Possible fix committed, please test.
Sorry, I can not test on android. My hopes that it will work now are small, but... let's see.
If this does not work, then.. I don;t know if it is possible to go full-in reflection style on `AwtColorArgumentHandler`, regarding `java.awt.Color`.

**Comment by hoijui** [comment]
I went ahead and moved (hopefully) all AWT related code into a different artifact:
`com.illposed.osc:java-se-addons`

As long as you don't list this as a dependency, you should be fine in Android now.

Please someone test on android, so I can make a release.

**Comment by JellevanAbbema** [comment]
I'm having a look at it right now. I'm using the 0.9-SNAPSHOT from sonatype but I'm not sure if that's the latest version. I'm unable to compile from the git source (a lot of problems running build). 
If the jar from sonatype is up to date then the fix did not work, I'm still having the same issue. From what I can tell the java-se-addons is not used as a dependency.

**Comment by JellevanAbbema** [comment]
> I did not release the snapshot before, sorry. I should have. it is stil a manual process. Now it should be up to date.
Yeah that's what I expected but not a problem at all, happens to the best of us.

But, at first sight, there don't seem to be any problems! Didn't really do a deep dive into it but I don't think there should be any problems with this fix, thank you very much! I really appreciate your work.

About my building issues: I just downloaded the repository in Intellij. I usually work with maven so I tried to just 'mvn clean install' the core artifact. I believe in the end it got stuck running the tests (`Tests run: 267, Failures: 1, Errors: 22, Skipped: 0`) but I also get allot of errors/warnings when I open the pom files (mainly the parent file). Didn't look further into it since I don't have the time to do so and I don't really need to build my own version.

**Comment by hoijui** [comment]
Ahh nice, thanks @JellevanAbbema !

**Comment by DodoSeal** [comment]
I don't know where any of the new fixes mentioned here are. I am on version 0.8 and a getting the same error with android currently.

**Comment by hoijui** [comment]
@DodoSeal 
they are in the `0.9-SNAPSHOT` release.
you can refer to it after putting this in your maven file:

```xml
	<repositories>
		<repository>
			<id>ossrh</id>
			<url>https://oss.sonatype.org/content/repositories/snapshots</url>
		</repository>
	</repositories>
```
