### ISSUE TITLE
Need example of OSCPortIn code

### ISSUE THREAD

**Issue by DiMoSe** [hoijui/JavaOSC#61]
Sorry if this isn't the right place to ask, but I need a PortIn example. There isn't one linked in the Readme for that part and the collider example only sends osc out.

**Comment by hoijui** [comment]
There is an example in the classes comment:
https://github.com/hoijui/JavaOSC/blob/master/modules/core/src/main/java/com/illposed/osc/transport/OSCPortIn.java#L29

good luck! :-)
