### ISSUE TITLE
Single socket for sending and receiving data

### ISSUE THREAD

**Issue by Burtan** [hoijui/JavaOSC#63]
Hey,

some clients for OSC like x32 mixer from Behringer require to have one port for incoming and outgoing messages. That is currently not possible. I have merged the functions of the OscPortIn and OscPortOut. Would you take a pull request to include the OscPortInOut?

Thanks :)

**Comment by nsowen** [comment]
As I also could not make JavaOSC communicate bi-directionally with X32, I submitted the following PR which allows using the OSCPortOut "Transport" to be used in a new OSCPortIn: https://github.com/hoijui/JavaOSC/pull/66

Kindly check if that also works for you or maybe your approach is even better?

**Comment by hoijui** [comment]
Closing as duplicate of #40
