### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by trackme518** [hoijui/JavaOSC#70]
Hi,
release on github is missing - but present on maven repo - maybe copy here as well?

**Comment by hoijui** [comment]
why?
I have very little time, and this is just extra work in my eyes, without a good reason.

**Comment by trackme518** [comment]
But still have time to reply to comments :-). Well, if you take the effort to make it open source on github why NOT to provide a build release? Without precompiled binaries it take extra time and effort for everyone to build from source not to mention that most people will simply not be able to build it. It would be nice to have some examples as well - how to parse messages etc. If you are having this repo just to archive the code then I guess it's fine - you can do whatever you like of course. I was just providing feedback in my free time on what could be improved, I am not your boss.

**Comment by hoijui** [comment]
precompiled binaries are in the maven central repo, which is also used by Gradle.
writing java/Kotlin/<other JVM based> software not using these tools/repos is pretty bad practice in my eyes, and I will not spend extra time to support it.
you can download manually from maven central too.
I took over this repo in 2012. people and their lives change.
Feel free to fork and put the maintenance in yourself.
Examples are already there in the JavaDoc. The first ten years I maintained this software, nobody had an issue in finding the examples and in using the maven releases (except there were bugs of course).
